jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        os: [ ubuntu-latest ]
        python-version: [ '2.7.17', '3.6.10' ]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}

    - name: Kaggle deploy as new
      uses: joelhanson/kaggle-kernel-actions
      with:
        kaggle_username: ${{ secrets.kaggle_username }}
        kaggle_key: ${{ secrets.kaggle_key }}
        kaggle_make_new_kernel: true
        kernel_id: <username>/<kernel_slug>
        code_file_path: <folder>/<file_path_to.ipynb>
        kernel_title: <kernel_title>
        language: python
        kernel_type: notebook
        is_private: true
        enable_gpu: false
        enable_internet: false
        competition: titanic
        submit_to_competition: false
        collect_output: true

    - name: Download outputs
      uses: actions/upload-artifact@v1
      with:
        name: outputs
        path: outputs/outputs.zijobs:
            deploy:
                  runs-on: ubuntu-latest
                        strategy:
                                matrix:
                                          os: [ ubuntu-latest, macos-latest ]
                                                    os: [ ubuntu-latest ]
                                                              python-version: [ '2.7.17', '3.6.10' ]
                                                                    name: Python ${{ matrix.python-version }} ${{ matrix.os }}

                                                                          - name: Kaggle deploy as new
                                                                                  uses: joelhanson/kaggle-kernel-actions
                                                                                          with:
                                                                                                    kaggle_username: ${{ secrets.kaggle_username }}
                                                                                                              kaggle_key: ${{ secrets.kaggle_key }}
                                                                                                                        kaggle_make_new_kernel: true
                                                                                                                                  kernel_id: <username>/<kernel_slug>
                                                                                                                                            code_file_path: <folder>/<file_path_to.ipynb>
                                                                                                                                                      kernel_title: <kernel_title>
                                                                                                                                                                language: python
                                                                                                                                                                          kernel_type: notebook
                                                                                                                                                                                    is_private: true
                                                                                                                                                                                              enable_gpu: false
                                                                                                                                                                                                        enable_internet: false
                                                                                                                                                                                                                  competition: titanic
                                                                                                                                                                                                                            submit_to_competition: false
                                                                                                                                                                                                                                      collect_output: true

                                                                                                                                                                                                                                            - name: Download outputs
                                                                                                                                                                                                                                                    uses: actions/upload-artifact@v1
                                                                                                                                                                                                                                                            with:
                                                                                                                                                                                                                                                                      name: outputs
                                                                                                                                                                                                                                                                                path: outputs/outputs.zipp
